# IMPORTING STANDARD PACKAGES
import os

REDIRECT_PAGE = os.getenv("REDIRECT_PAGE")
DOMAIN_URL = os.getenv("DOMAIN_URL")

# LINKS AND FRONTEND URLS
BASE_FRONTEND_URL = os.getenv("FRONTEND_URL")
FRONTEND_MAIN_PAGE = os.getenv("FRONTEND_MAIN_PAGE")
FRONTEND_LOGIN_PAGE = os.getenv("FRONTEND_LOGIN_PAGE")