# Generated by Django 4.1.5 on 2023-02-20 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurantuser',
            name='has_used_free_trial',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='restaurantuser',
            name='referral_code',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
