# Generated by Django 4.1.3 on 2023-01-23 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_baseuser_alter_restaurantuser_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurantuser',
            name='stripe_customer_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='restaurantuser',
            name='stripe_subscription_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
