# Generated by Django 4.1.3 on 2023-01-25 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_restaurantuser_stripe_customer_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='restaurantuser',
            name='stripe_customer_id',
        ),
        migrations.AlterField(
            model_name='restaurantuser',
            name='stripe_subscription_id',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
