# Generated by Django 4.1.3 on 2023-01-04 16:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0002_category_description_category_isactive_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='iconId',
        ),
    ]
